package br.com.druid.sdp.model;

public enum ExecutionLogEvent {
	CUSTOMER_CREATION,
	PROTOCOL_CREATION_SUBSCRIPTION,
	PROTOCOL_CANCELLATION_SUBSCRIPTION,
	SERVICE_PROVIDER_NOTIFICATION,
	SUBSCRIPTION_CREATION,
	SUBSCRIPTION_DELETION
}
